#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := app-template

include $(IDF_PATH)/make/project.mk

CFLAGS += -D__SUPPRESSANYOUTPUT__
CFLAGS += -Wno-unused-function -Wno-unused-parameter -Wno-implicit-function-declaration
